//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProducts.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name cod_prod from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProducts", ReplyAction="*")]
        ClientProducts.ServiceReference1.AddProductsResponse AddProducts(ClientProducts.ServiceReference1.AddProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientProducts.ServiceReference1.AddProductsResponse> AddProductsAsync(ClientProducts.ServiceReference1.AddProductsRequest request);
        
        // CODEGEN: Generating message contract since element name cod_prod from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddClients", ReplyAction="*")]
        ClientProducts.ServiceReference1.AddClientsResponse AddClients(ClientProducts.ServiceReference1.AddClientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddClients", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientProducts.ServiceReference1.AddClientsResponse> AddClientsAsync(ClientProducts.ServiceReference1.AddClientsRequest request);
        
        // CODEGEN: Generating message contract since element name comment from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddComments", ReplyAction="*")]
        ClientProducts.ServiceReference1.AddCommentsResponse AddComments(ClientProducts.ServiceReference1.AddCommentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddComments", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientProducts.ServiceReference1.AddCommentsResponse> AddCommentsAsync(ClientProducts.ServiceReference1.AddCommentsRequest request);
        
        // CODEGEN: Generating message contract since element name cod_prod from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProducts", ReplyAction="*")]
        ClientProducts.ServiceReference1.DeleteProductsResponse DeleteProducts(ClientProducts.ServiceReference1.DeleteProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientProducts.ServiceReference1.DeleteProductsResponse> DeleteProductsAsync(ClientProducts.ServiceReference1.DeleteProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteClients", ReplyAction="*")]
        void DeleteClients(int id_cl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteClients", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteClientsAsync(int id_cl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteComments", ReplyAction="*")]
        void DeleteComments(int id_cm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteComments", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteCommentsAsync(int id_cm);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateClients", ReplyAction="*")]
        ClientProducts.ServiceReference1.UpdateClientsResponse UpdateClients(ClientProducts.ServiceReference1.UpdateClientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateClients", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientProducts.ServiceReference1.UpdateClientsResponse> UpdateClientsAsync(ClientProducts.ServiceReference1.UpdateClientsRequest request);
        
        // CODEGEN: Generating message contract since element name cod_prod from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProducts", ReplyAction="*")]
        ClientProducts.ServiceReference1.UpdateProductsResponse UpdateProducts(ClientProducts.ServiceReference1.UpdateProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientProducts.ServiceReference1.UpdateProductsResponse> UpdateProductsAsync(ClientProducts.ServiceReference1.UpdateProductsRequest request);
        
        // CODEGEN: Generating message contract since element name comment from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateComments", ReplyAction="*")]
        ClientProducts.ServiceReference1.UpdateCommentsResponse UpdateComments(ClientProducts.ServiceReference1.UpdateCommentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateComments", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientProducts.ServiceReference1.UpdateCommentsResponse> UpdateCommentsAsync(ClientProducts.ServiceReference1.UpdateCommentsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProducts", Namespace="http://tempuri.org/", Order=0)]
        public ClientProducts.ServiceReference1.AddProductsRequestBody Body;
        
        public AddProductsRequest() {
        }
        
        public AddProductsRequest(ClientProducts.ServiceReference1.AddProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cod_prod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string availability;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string best_seller;
        
        public AddProductsRequestBody() {
        }
        
        public AddProductsRequestBody(string cod_prod, string name, int price, string availability, string best_seller) {
            this.cod_prod = cod_prod;
            this.name = name;
            this.price = price;
            this.availability = availability;
            this.best_seller = best_seller;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientProducts.ServiceReference1.AddProductsResponseBody Body;
        
        public AddProductsResponse() {
        }
        
        public AddProductsResponse(ClientProducts.ServiceReference1.AddProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddProductsResponseBody {
        
        public AddProductsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddClientsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddClients", Namespace="http://tempuri.org/", Order=0)]
        public ClientProducts.ServiceReference1.AddClientsRequestBody Body;
        
        public AddClientsRequest() {
        }
        
        public AddClientsRequest(ClientProducts.ServiceReference1.AddClientsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddClientsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_cl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cod_prod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string phone;
        
        public AddClientsRequestBody() {
        }
        
        public AddClientsRequestBody(int id_cl, string cod_prod, string name, string address, string phone) {
            this.id_cl = id_cl;
            this.cod_prod = cod_prod;
            this.name = name;
            this.address = address;
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddClientsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddClientsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientProducts.ServiceReference1.AddClientsResponseBody Body;
        
        public AddClientsResponse() {
        }
        
        public AddClientsResponse(ClientProducts.ServiceReference1.AddClientsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddClientsResponseBody {
        
        public AddClientsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCommentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddComments", Namespace="http://tempuri.org/", Order=0)]
        public ClientProducts.ServiceReference1.AddCommentsRequestBody Body;
        
        public AddCommentsRequest() {
        }
        
        public AddCommentsRequest(ClientProducts.ServiceReference1.AddCommentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCommentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_cm;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id_cl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public char rating;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string comment;
        
        public AddCommentsRequestBody() {
        }
        
        public AddCommentsRequestBody(int id_cm, int id_cl, char rating, string comment) {
            this.id_cm = id_cm;
            this.id_cl = id_cl;
            this.rating = rating;
            this.comment = comment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCommentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCommentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientProducts.ServiceReference1.AddCommentsResponseBody Body;
        
        public AddCommentsResponse() {
        }
        
        public AddCommentsResponse(ClientProducts.ServiceReference1.AddCommentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddCommentsResponseBody {
        
        public AddCommentsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProducts", Namespace="http://tempuri.org/", Order=0)]
        public ClientProducts.ServiceReference1.DeleteProductsRequestBody Body;
        
        public DeleteProductsRequest() {
        }
        
        public DeleteProductsRequest(ClientProducts.ServiceReference1.DeleteProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteProductsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cod_prod;
        
        public DeleteProductsRequestBody() {
        }
        
        public DeleteProductsRequestBody(string cod_prod) {
            this.cod_prod = cod_prod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientProducts.ServiceReference1.DeleteProductsResponseBody Body;
        
        public DeleteProductsResponse() {
        }
        
        public DeleteProductsResponse(ClientProducts.ServiceReference1.DeleteProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteProductsResponseBody {
        
        public DeleteProductsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateClientsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateClients", Namespace="http://tempuri.org/", Order=0)]
        public ClientProducts.ServiceReference1.UpdateClientsRequestBody Body;
        
        public UpdateClientsRequest() {
        }
        
        public UpdateClientsRequest(ClientProducts.ServiceReference1.UpdateClientsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateClientsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_cl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string phone;
        
        public UpdateClientsRequestBody() {
        }
        
        public UpdateClientsRequestBody(int id_cl, string name, string address, string phone) {
            this.id_cl = id_cl;
            this.name = name;
            this.address = address;
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateClientsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateClientsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientProducts.ServiceReference1.UpdateClientsResponseBody Body;
        
        public UpdateClientsResponse() {
        }
        
        public UpdateClientsResponse(ClientProducts.ServiceReference1.UpdateClientsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateClientsResponseBody {
        
        public UpdateClientsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProducts", Namespace="http://tempuri.org/", Order=0)]
        public ClientProducts.ServiceReference1.UpdateProductsRequestBody Body;
        
        public UpdateProductsRequest() {
        }
        
        public UpdateProductsRequest(ClientProducts.ServiceReference1.UpdateProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProductsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cod_prod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string availability;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string best_seller;
        
        public UpdateProductsRequestBody() {
        }
        
        public UpdateProductsRequestBody(string cod_prod, string name, int price, string availability, string best_seller) {
            this.cod_prod = cod_prod;
            this.name = name;
            this.price = price;
            this.availability = availability;
            this.best_seller = best_seller;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientProducts.ServiceReference1.UpdateProductsResponseBody Body;
        
        public UpdateProductsResponse() {
        }
        
        public UpdateProductsResponse(ClientProducts.ServiceReference1.UpdateProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateProductsResponseBody {
        
        public UpdateProductsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCommentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateComments", Namespace="http://tempuri.org/", Order=0)]
        public ClientProducts.ServiceReference1.UpdateCommentsRequestBody Body;
        
        public UpdateCommentsRequest() {
        }
        
        public UpdateCommentsRequest(ClientProducts.ServiceReference1.UpdateCommentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCommentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_cm;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id_cl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public char rating;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string comment;
        
        public UpdateCommentsRequestBody() {
        }
        
        public UpdateCommentsRequestBody(int id_cm, int id_cl, char rating, string comment) {
            this.id_cm = id_cm;
            this.id_cl = id_cl;
            this.rating = rating;
            this.comment = comment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCommentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCommentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientProducts.ServiceReference1.UpdateCommentsResponseBody Body;
        
        public UpdateCommentsResponse() {
        }
        
        public UpdateCommentsResponse(ClientProducts.ServiceReference1.UpdateCommentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateCommentsResponseBody {
        
        public UpdateCommentsResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClientProducts.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClientProducts.ServiceReference1.WebService1Soap>, ClientProducts.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientProducts.ServiceReference1.AddProductsResponse ClientProducts.ServiceReference1.WebService1Soap.AddProducts(ClientProducts.ServiceReference1.AddProductsRequest request) {
            return base.Channel.AddProducts(request);
        }
        
        public void AddProducts(string cod_prod, string name, int price, string availability, string best_seller) {
            ClientProducts.ServiceReference1.AddProductsRequest inValue = new ClientProducts.ServiceReference1.AddProductsRequest();
            inValue.Body = new ClientProducts.ServiceReference1.AddProductsRequestBody();
            inValue.Body.cod_prod = cod_prod;
            inValue.Body.name = name;
            inValue.Body.price = price;
            inValue.Body.availability = availability;
            inValue.Body.best_seller = best_seller;
            ClientProducts.ServiceReference1.AddProductsResponse retVal = ((ClientProducts.ServiceReference1.WebService1Soap)(this)).AddProducts(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientProducts.ServiceReference1.AddProductsResponse> ClientProducts.ServiceReference1.WebService1Soap.AddProductsAsync(ClientProducts.ServiceReference1.AddProductsRequest request) {
            return base.Channel.AddProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientProducts.ServiceReference1.AddProductsResponse> AddProductsAsync(string cod_prod, string name, int price, string availability, string best_seller) {
            ClientProducts.ServiceReference1.AddProductsRequest inValue = new ClientProducts.ServiceReference1.AddProductsRequest();
            inValue.Body = new ClientProducts.ServiceReference1.AddProductsRequestBody();
            inValue.Body.cod_prod = cod_prod;
            inValue.Body.name = name;
            inValue.Body.price = price;
            inValue.Body.availability = availability;
            inValue.Body.best_seller = best_seller;
            return ((ClientProducts.ServiceReference1.WebService1Soap)(this)).AddProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientProducts.ServiceReference1.AddClientsResponse ClientProducts.ServiceReference1.WebService1Soap.AddClients(ClientProducts.ServiceReference1.AddClientsRequest request) {
            return base.Channel.AddClients(request);
        }
        
        public void AddClients(int id_cl, string cod_prod, string name, string address, string phone) {
            ClientProducts.ServiceReference1.AddClientsRequest inValue = new ClientProducts.ServiceReference1.AddClientsRequest();
            inValue.Body = new ClientProducts.ServiceReference1.AddClientsRequestBody();
            inValue.Body.id_cl = id_cl;
            inValue.Body.cod_prod = cod_prod;
            inValue.Body.name = name;
            inValue.Body.address = address;
            inValue.Body.phone = phone;
            ClientProducts.ServiceReference1.AddClientsResponse retVal = ((ClientProducts.ServiceReference1.WebService1Soap)(this)).AddClients(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientProducts.ServiceReference1.AddClientsResponse> ClientProducts.ServiceReference1.WebService1Soap.AddClientsAsync(ClientProducts.ServiceReference1.AddClientsRequest request) {
            return base.Channel.AddClientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientProducts.ServiceReference1.AddClientsResponse> AddClientsAsync(int id_cl, string cod_prod, string name, string address, string phone) {
            ClientProducts.ServiceReference1.AddClientsRequest inValue = new ClientProducts.ServiceReference1.AddClientsRequest();
            inValue.Body = new ClientProducts.ServiceReference1.AddClientsRequestBody();
            inValue.Body.id_cl = id_cl;
            inValue.Body.cod_prod = cod_prod;
            inValue.Body.name = name;
            inValue.Body.address = address;
            inValue.Body.phone = phone;
            return ((ClientProducts.ServiceReference1.WebService1Soap)(this)).AddClientsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientProducts.ServiceReference1.AddCommentsResponse ClientProducts.ServiceReference1.WebService1Soap.AddComments(ClientProducts.ServiceReference1.AddCommentsRequest request) {
            return base.Channel.AddComments(request);
        }
        
        public void AddComments(int id_cm, int id_cl, char rating, string comment) {
            ClientProducts.ServiceReference1.AddCommentsRequest inValue = new ClientProducts.ServiceReference1.AddCommentsRequest();
            inValue.Body = new ClientProducts.ServiceReference1.AddCommentsRequestBody();
            inValue.Body.id_cm = id_cm;
            inValue.Body.id_cl = id_cl;
            inValue.Body.rating = rating;
            inValue.Body.comment = comment;
            ClientProducts.ServiceReference1.AddCommentsResponse retVal = ((ClientProducts.ServiceReference1.WebService1Soap)(this)).AddComments(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientProducts.ServiceReference1.AddCommentsResponse> ClientProducts.ServiceReference1.WebService1Soap.AddCommentsAsync(ClientProducts.ServiceReference1.AddCommentsRequest request) {
            return base.Channel.AddCommentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientProducts.ServiceReference1.AddCommentsResponse> AddCommentsAsync(int id_cm, int id_cl, char rating, string comment) {
            ClientProducts.ServiceReference1.AddCommentsRequest inValue = new ClientProducts.ServiceReference1.AddCommentsRequest();
            inValue.Body = new ClientProducts.ServiceReference1.AddCommentsRequestBody();
            inValue.Body.id_cm = id_cm;
            inValue.Body.id_cl = id_cl;
            inValue.Body.rating = rating;
            inValue.Body.comment = comment;
            return ((ClientProducts.ServiceReference1.WebService1Soap)(this)).AddCommentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientProducts.ServiceReference1.DeleteProductsResponse ClientProducts.ServiceReference1.WebService1Soap.DeleteProducts(ClientProducts.ServiceReference1.DeleteProductsRequest request) {
            return base.Channel.DeleteProducts(request);
        }
        
        public void DeleteProducts(string cod_prod) {
            ClientProducts.ServiceReference1.DeleteProductsRequest inValue = new ClientProducts.ServiceReference1.DeleteProductsRequest();
            inValue.Body = new ClientProducts.ServiceReference1.DeleteProductsRequestBody();
            inValue.Body.cod_prod = cod_prod;
            ClientProducts.ServiceReference1.DeleteProductsResponse retVal = ((ClientProducts.ServiceReference1.WebService1Soap)(this)).DeleteProducts(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientProducts.ServiceReference1.DeleteProductsResponse> ClientProducts.ServiceReference1.WebService1Soap.DeleteProductsAsync(ClientProducts.ServiceReference1.DeleteProductsRequest request) {
            return base.Channel.DeleteProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientProducts.ServiceReference1.DeleteProductsResponse> DeleteProductsAsync(string cod_prod) {
            ClientProducts.ServiceReference1.DeleteProductsRequest inValue = new ClientProducts.ServiceReference1.DeleteProductsRequest();
            inValue.Body = new ClientProducts.ServiceReference1.DeleteProductsRequestBody();
            inValue.Body.cod_prod = cod_prod;
            return ((ClientProducts.ServiceReference1.WebService1Soap)(this)).DeleteProductsAsync(inValue);
        }
        
        public void DeleteClients(int id_cl) {
            base.Channel.DeleteClients(id_cl);
        }
        
        public System.Threading.Tasks.Task DeleteClientsAsync(int id_cl) {
            return base.Channel.DeleteClientsAsync(id_cl);
        }
        
        public void DeleteComments(int id_cm) {
            base.Channel.DeleteComments(id_cm);
        }
        
        public System.Threading.Tasks.Task DeleteCommentsAsync(int id_cm) {
            return base.Channel.DeleteCommentsAsync(id_cm);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientProducts.ServiceReference1.UpdateClientsResponse ClientProducts.ServiceReference1.WebService1Soap.UpdateClients(ClientProducts.ServiceReference1.UpdateClientsRequest request) {
            return base.Channel.UpdateClients(request);
        }
        
        public void UpdateClients(int id_cl, string name, string address, string phone) {
            ClientProducts.ServiceReference1.UpdateClientsRequest inValue = new ClientProducts.ServiceReference1.UpdateClientsRequest();
            inValue.Body = new ClientProducts.ServiceReference1.UpdateClientsRequestBody();
            inValue.Body.id_cl = id_cl;
            inValue.Body.name = name;
            inValue.Body.address = address;
            inValue.Body.phone = phone;
            ClientProducts.ServiceReference1.UpdateClientsResponse retVal = ((ClientProducts.ServiceReference1.WebService1Soap)(this)).UpdateClients(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientProducts.ServiceReference1.UpdateClientsResponse> ClientProducts.ServiceReference1.WebService1Soap.UpdateClientsAsync(ClientProducts.ServiceReference1.UpdateClientsRequest request) {
            return base.Channel.UpdateClientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientProducts.ServiceReference1.UpdateClientsResponse> UpdateClientsAsync(int id_cl, string name, string address, string phone) {
            ClientProducts.ServiceReference1.UpdateClientsRequest inValue = new ClientProducts.ServiceReference1.UpdateClientsRequest();
            inValue.Body = new ClientProducts.ServiceReference1.UpdateClientsRequestBody();
            inValue.Body.id_cl = id_cl;
            inValue.Body.name = name;
            inValue.Body.address = address;
            inValue.Body.phone = phone;
            return ((ClientProducts.ServiceReference1.WebService1Soap)(this)).UpdateClientsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientProducts.ServiceReference1.UpdateProductsResponse ClientProducts.ServiceReference1.WebService1Soap.UpdateProducts(ClientProducts.ServiceReference1.UpdateProductsRequest request) {
            return base.Channel.UpdateProducts(request);
        }
        
        public void UpdateProducts(string cod_prod, string name, int price, string availability, string best_seller) {
            ClientProducts.ServiceReference1.UpdateProductsRequest inValue = new ClientProducts.ServiceReference1.UpdateProductsRequest();
            inValue.Body = new ClientProducts.ServiceReference1.UpdateProductsRequestBody();
            inValue.Body.cod_prod = cod_prod;
            inValue.Body.name = name;
            inValue.Body.price = price;
            inValue.Body.availability = availability;
            inValue.Body.best_seller = best_seller;
            ClientProducts.ServiceReference1.UpdateProductsResponse retVal = ((ClientProducts.ServiceReference1.WebService1Soap)(this)).UpdateProducts(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientProducts.ServiceReference1.UpdateProductsResponse> ClientProducts.ServiceReference1.WebService1Soap.UpdateProductsAsync(ClientProducts.ServiceReference1.UpdateProductsRequest request) {
            return base.Channel.UpdateProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientProducts.ServiceReference1.UpdateProductsResponse> UpdateProductsAsync(string cod_prod, string name, int price, string availability, string best_seller) {
            ClientProducts.ServiceReference1.UpdateProductsRequest inValue = new ClientProducts.ServiceReference1.UpdateProductsRequest();
            inValue.Body = new ClientProducts.ServiceReference1.UpdateProductsRequestBody();
            inValue.Body.cod_prod = cod_prod;
            inValue.Body.name = name;
            inValue.Body.price = price;
            inValue.Body.availability = availability;
            inValue.Body.best_seller = best_seller;
            return ((ClientProducts.ServiceReference1.WebService1Soap)(this)).UpdateProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientProducts.ServiceReference1.UpdateCommentsResponse ClientProducts.ServiceReference1.WebService1Soap.UpdateComments(ClientProducts.ServiceReference1.UpdateCommentsRequest request) {
            return base.Channel.UpdateComments(request);
        }
        
        public void UpdateComments(int id_cm, int id_cl, char rating, string comment) {
            ClientProducts.ServiceReference1.UpdateCommentsRequest inValue = new ClientProducts.ServiceReference1.UpdateCommentsRequest();
            inValue.Body = new ClientProducts.ServiceReference1.UpdateCommentsRequestBody();
            inValue.Body.id_cm = id_cm;
            inValue.Body.id_cl = id_cl;
            inValue.Body.rating = rating;
            inValue.Body.comment = comment;
            ClientProducts.ServiceReference1.UpdateCommentsResponse retVal = ((ClientProducts.ServiceReference1.WebService1Soap)(this)).UpdateComments(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientProducts.ServiceReference1.UpdateCommentsResponse> ClientProducts.ServiceReference1.WebService1Soap.UpdateCommentsAsync(ClientProducts.ServiceReference1.UpdateCommentsRequest request) {
            return base.Channel.UpdateCommentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientProducts.ServiceReference1.UpdateCommentsResponse> UpdateCommentsAsync(int id_cm, int id_cl, char rating, string comment) {
            ClientProducts.ServiceReference1.UpdateCommentsRequest inValue = new ClientProducts.ServiceReference1.UpdateCommentsRequest();
            inValue.Body = new ClientProducts.ServiceReference1.UpdateCommentsRequestBody();
            inValue.Body.id_cm = id_cm;
            inValue.Body.id_cl = id_cl;
            inValue.Body.rating = rating;
            inValue.Body.comment = comment;
            return ((ClientProducts.ServiceReference1.WebService1Soap)(this)).UpdateCommentsAsync(inValue);
        }
    }
}
